apiVersion: v1
kind: Namespace
metadata:
  name: iam-example
  annotations:
    iam.amazonaws.com/permitted: ".*"

---
apiVersion: v1
kind: Pod
metadata:
  name: iam-example
  namespace: iam-example
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::059300324029:role/iamdemo-s3-access
spec:
  containers:
  - name: aws-cli
    image: neovatar/aws-cli
    command: ["sleep"]
    args: ["60m"]
  restartPolicy: OnFailure

---
apiVersion: v1
kind: Pod
metadata:
  name: iam-example-noaccess
  namespace: iam-example
spec:
  containers:
  - name: aws-cli
    image: neovatar/aws-cli
    command: ["sleep"]
    args: ["60m"]
  restartPolicy: OnFailure